# Generated by Django 2.1.2 on 2018-11-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=150)),
                ('valor_compra', models.CharField(blank=True, max_length=150)),
                ('valor_aluguel', models.CharField(blank=True, max_length=150)),
                ('endereco', models.CharField(blank=True, max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='clientes_fotos')),
            ],
        ),
    ]
